spring:
  application:
    name: "ProductService"
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/productDB
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8084/eureka/

